# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'navbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NavBar(object):
    def setupUi(self, NavBar):
        NavBar.setObjectName("NavBar")
        NavBar.resize(260, 930)
        self.frame = QtWidgets.QFrame(NavBar)
        self.frame.setGeometry(QtCore.QRect(0, 0, 260, 930))
        self.frame.setStyleSheet("background-color: #303657;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setSpacing(30)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/user64.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setAcceptDrops(False)
        self.pushButton_3.setStyleSheet("border-style: none;\n"
"color: white;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"background-color: #3f4773;\n"
"border-radius: 10;\n"
"text-align: left;\n"
"padding-left: 10;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/home-2-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setAcceptDrops(False)
        self.pushButton_2.setStyleSheet("border-style: none;\n"
"color: white;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"background-color: #3f4773;\n"
"border-radius: 10;\n"
"text-align: left;\n"
"padding-left: 10;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/bed-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setAcceptDrops(False)
        self.pushButton_4.setStyleSheet("border-style: none;\n"
"color: white;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"background-color: #3f4773;\n"
"border-radius: 10;\n"
"text-align: left;\n"
"padding-left: 10;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/in-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setAcceptDrops(False)
        self.pushButton_5.setStyleSheet("border-style: none;\n"
"color: white;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"background-color: #3f4773;\n"
"border-radius: 10;\n"
"text-align: left;\n"
"padding-left: 10;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/out-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setAcceptDrops(False)
        self.pushButton_7.setStyleSheet("border-style: none;\n"
"color: white;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"background-color: #3f4773;\n"
"border-radius: 10;\n"
"text-align: left;\n"
"padding-left: 10;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/room-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon4)
        self.pushButton_7.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_4.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setAcceptDrops(False)
        self.pushButton_6.setStyleSheet("border-style: none;\n"
"color: white;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"background-color: #3f4773;\n"
"border-radius: 10;\n"
"text-align: left;\n"
"padding-left: 10;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/service-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setAcceptDrops(False)
        self.pushButton_8.setStyleSheet("border-style: none;\n"
"color: white;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"background-color: #3f4773;\n"
"border-radius: 10;\n"
"text-align: left;\n"
"padding-left: 10;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/account-logout-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon6)
        self.pushButton_8.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_4.addWidget(self.pushButton_8)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)

        self.retranslateUi(NavBar)
        QtCore.QMetaObject.connectSlotsByName(NavBar)

    def retranslateUi(self, NavBar):
        _translate = QtCore.QCoreApplication.translate
        NavBar.setWindowTitle(_translate("NavBar", "Form"))
        self.label_2.setText(_translate("NavBar", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Minh Duong</span></p></body></html>"))
        self.pushButton_3.setText(_translate("NavBar", "    Dashboard"))
        self.pushButton_2.setText(_translate("NavBar", "    Booking"))
        self.pushButton_4.setText(_translate("NavBar", "    Checkin"))
        self.pushButton_5.setText(_translate("NavBar", "    Checkout"))
        self.pushButton_7.setText(_translate("NavBar", "    Rooms"))
        self.pushButton_6.setText(_translate("NavBar", "    Services"))
        self.pushButton_8.setText(_translate("NavBar", "    Sign out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NavBar = QtWidgets.QWidget()
    ui = Ui_NavBar()
    ui.setupUi(NavBar)
    NavBar.show()
    sys.exit(app.exec_())
